language: android
sudo: false
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-support
    - extra-android-m2repository
script:
  ./gradlew build